services:
  frontend:
    image: antoniopapa1991/admin-frontend
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - app

  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: project_laravel_admin_ms
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
    ports:
      - 9100:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - app

  db:
    container_name: admin_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: project_laravel_admin_ms
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - app
  redis:
    container_name: admin_redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admin_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - app

networks:
  app:
